language: ruby

sudo: false

cache: bundler

rvm:
  - 2.2
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 2.6

before_script:
  - git config --global user.email "travis@travis.ci"
  - git config --global user.name "Travis CI"

before_install:
  - |
    export RVM_CURRENT=`rvm current`
    if [ "${RVM_CURRENT}" != "ruby-2.2.7" ]; then
      gem --version
    else
      gem update --system
    fi
  - gem install bundler:'< 2'

script:
  - bundle exec rspec
  - bundle exec overcommit --sign
  - bundle exec overcommit --sign pre-commit
  - bundle exec overcommit --run
