language: ruby

sudo: false

cache: bundler

rvm:
  - 2.1
  - 2.2
  - 2.3.6
  - 2.4.3
  - 2.5.0

before_script:
  - git config --global user.email "travis@travis.ci"
  - git config --global user.name "Travis CI"

before_install:
  - '[[ "$TRAVIS_RUBY_VERSION" =~ "^jruby|^ruby 2.3|^ruby 2.4|^ruby 2.5" ]] && gem update --system || true'

script:
  - bundle exec rspec
  # Skip Overcommit on JRuby since it's unstable and doesn't actually test Overcommit
  - '[[ $TRAVIS_RUBY_VERSION =~ ^jruby ]] && exit || true'
  - bundle exec overcommit --sign
  - bundle exec overcommit --sign pre-commit
  - bundle exec overcommit --run
