version: "{build}"

clone_depth: 1

environment:
  matrix:
    - RUBY_FOLDER_VERSION: "22"
    - RUBY_FOLDER_VERSION: "22-x64"
    - RUBY_FOLDER_VERSION: "23"
    - RUBY_FOLDER_VERSION: "23-x64"
    - RUBY_FOLDER_VERSION: "24"
    - RUBY_FOLDER_VERSION: "24-x64"
    - RUBY_FOLDER_VERSION: "25"
    - RUBY_FOLDER_VERSION: "25-x64"
    - RUBY_FOLDER_VERSION: "26"
    - RUBY_FOLDER_VERSION: "26-x64"
matrix:
  fast_finish: true

cache:
  # Cache installed gems unless dependencies change
  - vendor\bundle -> Gemfile,overcommit.gemspec

install:
  # Add ruby executables to PATH
  - set PATH=C:\Ruby%RUBY_FOLDER_VERSION%\bin;%PATH%
  - echo %PATH%

  # Print version and location for pre-installed grep
  - grep --version
  - where grep

  # Print version and location for pre-installed git
  - git --version
  - where git

  # Print version and location for pre-installed ruby
  - ruby --version
  - where ruby

  # Install latest version of RubyGems
  - gem update --system --no-rdoc
  - gem --version
  - where gem

  # Install latest Bundler to work around version issues
  - gem install bundler:'< 2' --force
  - where bundler

  # Install ruby dependencies
  - bundle install --retry 3 --path vendor\bundle

build: off

before_test:
  # Necessary for AuthorName and AuthorEmail pre-commit hooks to pass
  - git config --global user.email "appveyor@appveyor.ci"
  - git config --global user.name "Appveyor CI"

  # Ignore CRLF conversion warnings
  - git config --global core.safecrlf false

test_script:
  - bundle exec rspec --tty --backtrace --color
  - bundle exec overcommit --sign
  - bundle exec overcommit --sign pre-commit
  - bundle exec overcommit --run
